### ISSUE TITLE
Error reporting should be selectable  for FE/BE

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#103]
Just an idea: it would be useful if one could select not only _if_, but also _where_ PHP errors should be displayed. Sometimes one just want to debug errors in the backend and there's no need that errors are displayed also in the frontend. 
Is this possible?

**Comment by NorHei** [comment]
At least it's possibly hard to do, as the Initialize Script isn't aware of being in the FE or BE ...
When The Page Id less Frontendpages are removed (Search, Account...), it would be a lot more easy , as all calls whith a page ID would mean we are in the frontend. 
So as soon as those id less pages are removed i give it a try. Setting this on Later for now .

Maybe Someone Else got a good idea how to identify FE/BE reliable in the Initialize.php.

**Comment by instantflorian** [comment]
It's not so important, was just an idea.

**Comment by NorHei** [comment]
You are perfectly right.

New Droplets are generated in  add_droplet.php.

In tools.php  line 29 they are deleted again, always ...
So the query in line 131 cannot return any values for this droplet as 
its already deleted .
So the hidden field cannot be populated and no droplet_id is sent to save.

So the Droplet is created , deleted , and then tried to edit ...

I added an if clause that only deletes the empty droplets on normal tool 
view, whithout do=something. This should do it.  Hopefully.




Am 25.01.2016 um 07:41 schrieb instantflorian:
> It's not so important, was just an idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/103#issuecomment-174417088>.
>

-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792
