### ISSUE TITLE
Add a history function to pages . 

### ISSUE THREAD

**Issue by NorHei** [WBCE/WBCE_CMS#113]
What the title says , any ideas welcome .

**Comment by digitalbricks** [comment]
Are you meaning a sort of versions or revisions? At least for WYSIWYG-sections there was (as far i know) a working implementation of versions in "extendedWYSIWYG" by Ralf Hertsch: [https://github.com/phpManufaktur/extendedWYSIWYG](https://github.com/phpManufaktur/extendedWYSIWYG)

**Comment by webbird** [comment]
I have to say that extendedWYSIWYG seems to have some caveats, especially if used with LEPTON. (Umlauts, quotes.) Apart of that, it should be a good basis.

**Comment by NorHei** [comment]
Basically i would prefer  full drafts and history for the complete page. 
And yess that would make problems whith modules like topics , procalendar or foldergallery.

**Comment by digitalbricks** [comment]
As in WB(CE) every module brings its own save routine, it's probably hard to find a system wide solution for this. As far as I understand, the underlying CM system isn't actually involved in saving content from a page section – that's the job of the `save.php` in each module. And as long the system isn't noticed on save event, it is likely unable to track the changes. 

In MODX Revolution for example there are several system events that are fired on several actions. So there is `OnDocFormSave` event you can hook on and do some actions. WB is lacking such event listeners and so I think i will get paintfull to get this job done. But actually i am not so deep involved in the WB(CE) code, so maybe there is a "hidden secret"?

**Comment by NorHei** [comment]
extendedWYSIWYG is a module issue not a core functionality. Feel Free to simply build one . 
If you need some extra functionality in the Core for this , have a word whith me :-)

**Comment by NorHei** [comment]
Sorry overlapping comments. 

Yes you got it right, thats something that is really needed. 
Admintools already have this in 1.2.x , possibly this is only for 1.3.x but its something thats coming on the long term
