### ISSUE TITLE
LDAP interface

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/WBCE_CMS#116]
the possibility to connect WB to an LDAP and manage users and groups in the LDAP instead of (or in addition to?) the backend has been requested several times. A simple approach would just disable user-management in the backend when an LDAP server is configured. Probably one just has to modify the login class, and maybe a few more places where uid/gid, permissions etc. are queried. One should probably keep the Admin group and user locally to ensure the correct uid/gid for these privileged accounts. 
Nice to have would be a backend interface to conveniently configure the parameters needed to talk to the LDAP server.

http://forum.wbce.org/post.php?tid=459

Just when writing this, it comes to my mind that another step would be to recycle WB's user- and group management to manage the ldap accounts. This however, requires more privileges on the ldap server, and maybe this is a second step which can be postponed to another implementation phase.
Martin

**Comment by webbird** [comment]
It should be quite easy to handle the authorization only via LDAP while still managing the permissions in WBCE. This would make the password field obsolet, while any permission checks are handled as before. The only additional need would be to list LDAP users and allow to import the required users into the WBCE database.
