### ISSUE TITLE
Create FileManager as Admintool

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#126]
The "FileManager" by seems to be a useful tool for managing media files. 
http://www.gerd-tentler.de/tools/filemanager/index.php?page=introduction
So we should test if it's possible to build a Admin tool from it.
Note! The first alpha release MAY NOT be published, it will be just a proof a concept. If its working generally, we HAVE to contact the developer and negotiate about the license terms. (I'm willing to donate an acceptable amount of money to him for this of course.)
See http://www.gerd-tentler.de/tools/filemanager/index.php?page=download

**Comment by instantflorian** [comment]
So due to the license restrictions a tool with a real open source license would be better. See http://forum.wbce.org/viewtopic.php?pid=4420#p4420 for proposals.

**Comment by NorHei** [comment]
Ei really thought of adding El Finder , as its being actively maintained 

last commit about 19 Hours ago 

btw thats a thing where class insert and BE filters would help alot :-)

**Comment by instantflorian** [comment]
yeah looks good

**Comment by webbird** [comment]
As far as I remember ELFinder is quite restricted concerning user permissions?

**Comment by NorHei** [comment]
As 1.2.x is a core release , that enables a lot of stuff for modules , ill look after this after 1.2.x is released . 
After the release i will build quite a lot of new modules.
