### ISSUE TITLE
Better DST / time zone management

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#148]
DST (Sommerzeit/Winterzeit) should be switched automatically instead of shifting the GMT timezone every 6 months.
Generally spoken, the time/date management of WBCE is still a mess and should be cleansed / basically reworked. Newer CMS use UTC.
[See thread in WBCE forum (german)](https://forum.wbce.org/viewtopic.php?id=751)

**Comment by NorHei** [comment]
Newer CMS use Locale Settings of PHP ... btw good point !
