### ISSUE TITLE
Replace Editarea with Ace

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#15]
About ACE: http://ace.c9.io/

**Comment by webbird** [comment]
Uhm, why? What's wrong with EditArea?

**Comment by instantflorian** [comment]
It is from 2010 and not maintained any more

**Comment by webbird** [comment]
Maybe ACE should be stripped then..

"Syntax highlighting for over 110 languages"

**Comment by webbird** [comment]
I've set vLater milestone, so we can do this in a later version (1.1?)
