### ISSUE TITLE
Replace JScalendar

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#16]
Instead: http://xdsoft.net/jqplugins/datetimepicker/

**Comment by webbird** [comment]
Why not using jQuery UI?

**Comment by instantflorian** [comment]
I don't know... if it's simple to implement, we can use it as well of course. I just copied the proposal from the WBCE forum ;)

**Comment by webbird** [comment]
Postponed to some later version

**Comment by NorHei** [comment]
Tha basic Jquery UI datepicker has no time option :-)
But someone wrote an addoun for UI.
http://trentrichardson.com/examples/timepicker/

It would be styled like the Jquery UI theme then.
