### ISSUE TITLE
Charset not configurable any more?

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#236]
Maybe I'm blind or too drunken, but I dont find the possibility to set the charset (Zeichensatz) in the new option dialogues any more...
(Furthermore, athough I know I'm not innocent of this at all, I'm getting irritated more and more due to this multiple Einstellungen stuff... Standard Einstellungen, System-Einstellungen, Mail-Einstellungen, Such-Einstellungen, Sicherheits Einstellungen, SEO/Metadaten-Einstellungen, Server-Einstellungen...
I'm always searching where to find this or that, it's annoying.)

**Comment by cwsoft** [comment]
Most times I need one or two trials to find some less used setting options. Splitting standard and server settings into two separate dialogues is a good step. However splitting out all the former settings like Email, Permission, Search, Media etc. seems a bit too much from a simple usability perspective. Maybe there is a chance to recombine those into one module again and use tabs and/or jQuery Filter to group or show/hide individual setting options.

**Comment by NorHei** [comment]
You got all options , write a Lister whith tabs in Frames, Move Some settings to another Settings modul. 
Its all modules now.  You can even just make a template for that in your BE Template.

For this release i think some resorting/renaming/clarifications will do , together  with some explanations. 

Personally i think having all settings in one big Blob of page was even worse. The old blob was completely unmaintainable , any fix resulted in a bunch of Problems  and the template was complete rubbish. 

"Such-Einstellungen" should contain all Settings about the Search module. 
"Mail-Einstellungen" anything about Mail 

Default Settings , should contain all system default values. Maybe it needs a better translation than Standard Einstellungen. 

In addition to that take a look at the additional text in the Selector as it explains alot. 

Pluging all funtionality into one module /script really sucks if you want to build enhanced Settings for a special purpose or if you want to add more settings for some extended features. 

I dont mind resorting the settings , and renaming the parts but building framed templates or AJAX loaded tabs is definedly out of shedule  for now.  Btw we could even use the Colorbox Module for that.

**Comment by instantflorian** [comment]
This is still open (missing charset setting option)

**Comment by instantflorian** [comment]
Dunno. Maybe for testing purposes or backward compatibility? What happens if a site with other charset setting than utf-8 is migrated to WBCE 1.2?

**Comment by NorHei** [comment]
It keeps its charset ... .. ok where you want the setting

**Comment by instantflorian** [comment]
at Systemeinstellungen pls

**Comment by instantflorian** [comment]
Charset selection has been added again, so I close this issue
