### ISSUE TITLE
Load frontend.js/css only when necessary

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#244]
See https://forum.wbce.org/viewtopic.php?id=1146
frontend.js and frontend.css (and maybe other scripts?) of a certain module should not be loaded when the only section of this section is not active.

**Comment by NorHei** [comment]
Thats what the insert class is for :-)
You can insert any JS metas CSS or HTML into the placeholders inside of the Template, but only if the module code is called.

**Comment by WebDesignWorx** [comment]
This issue is handled with https://github.com/WBCE/WBCE_CMS/pull/382
and can be closed.
