### ISSUE TITLE
Removing the default_theme will break some backend functionality 

### ISSUE THREAD

**Issue by cwsoft** [WBCE/WBCE_CMS#249]
After a fresh installation or upgrade, the "advancedThemeWBFlat" is the standard theme used in the WBCE backend, which is fine. 

It is possible, to uninstall the WBCE Default Theme (wbce/templates/default_theme) via the Backend (Addons->Templates->Uninstall) if this theme is not in use. Doing so, will break some backend functionality. Instead the backend page, the plain text message "Template File missing" is shown. Pages affected are (not concluding): Access->Users, Access->Groups, Addon->Modules|Templates|Languages->Details.

Generally the term "default_theme" is quite confusing, as the default theme (fresh installation and upgrade) is "advancedThemeWBFlat". It´s also not so easy to track which template file is used when and why. So if advancedThemeWBFlat theme is active and not modified by the user, why are some templates files used from "wbce/templates/default_theme" and some from "wbce/templates/advancedThemeWBFlat"?

In general I would suggest to get rid of the default_theme stuff in WBCE 1.2.x and just provide a message pointing to the missing file like: Template file 'template_file.htt' not found in theme folder '/templates/theme_name'. To fix the problem one would need to upload a working theme via FTP (e.g. advancedThemeWBFlat) and run the [reset_admin_theme](https://github.com/WBCE/wbce_tools/tree/master/reset_admin_theme) script to ensure a fully working WBCE version.

**Comment by NorHei** [comment]
Already done   040dc48 or onne before that 

the Theme does no longer appear in BE

**Comment by cwsoft** [comment]
@NorHei: Well it´s partly done. 

One can still delete wbce/templates/default_theme (e.g. during upgrade process, or via FTP due to clean up work). Result is a backend which works only partly as explained in more detail in the entry post of this issue. This is a odd behaviour. As a supporter I would bet on a broken upload via FTP as 50% of the backend works but the other 50% won´t. I would never figure out that 50% of the templates files are read from the theme I activated, while the other 50% of the files are read from wbce/templates/default_theme.

**Comment by NorHei** [comment]
You perfectly describe the behavior of good old WB classic :-)
Only difference is that i put the theme folder from admin  in the main template folder . 

As you can not delete the template set default by wb interface ... lets give it a try ..  

9cc928c

**Comment by cwsoft** [comment]
@NorHei: Scheint wir reden aneinander vorbei. 

Bei einer frischen Installation (oder Upgrade) wird das Backend-Theme "AdvancedThemeWBFlat" als Standard eingestellt. Soweit so gut. In dessen Themes Ordner "/templates/AdvancedThemeWBFlat/templates" befinden sich 21 Templatedateien (*.htt).

Mit Commit #9cc928ccaea5a223ec40d6d56e5951bf35045911 wurde das Theme "Default Theme based on Argos" enfernt. In dessen Themes Ordner "/templates/default_theme/templates" befanden sich 30 Templatedateien (*.htt). Sprich im AdvancedThemeWBFlat fehlen 9 Templatedateien des Backends. 

Besucht man nun z.B. Access -> Groups, Access -> Users etc., wird nachfolgende Fehlermeldung anstelle z.B. der Gruppenverwaltung angezeigt.

<img width="495" alt="template-missing" src="https://cloud.githubusercontent.com/assets/1426817/24872521/fa0fba8a-1e1d-11e7-9644-ce04b6156ecb.PNG">

Daher die Frage nach dem Sinn und Zwecks des "default_themes". Sprich ich denke wir müssten die 9 fehlenden *.htt Dateien ins AdvancedThemeWBFlat kopieren, dann können wir auf das default_theme verzichten. Das argos_theme_reloaded enthält 28 *.htt Dateien. Daher meine Verwirrung und Frage nach Sinn und Zweck des default_themes.

**Comment by NorHei** [comment]
Jep, thats the solution ! Copy the missing files into the templates 
Can you please do this ? As i am away from my Dev Machine , no Passwords nothing :-(

Its better to simplify things and most files of the Theme become obsolete as soon as the Pages are replaced by modules.

**Comment by NorHei** [comment]
Thx alot !

**Comment by instantflorian** [comment]
I'm not very happy with this. So the Flat theme works, but already Argos Reloaded (which is shipped as alternative template) probably won't and neither Beesign CE will. I would prefer having an invisible Fallback template for this cases.

**Comment by cwsoft** [comment]
I am not happy with the backend theme stuff at all, as it is by no means transparent. Splitting settings in its onw PHP templates won´t make it easier for theme designers in the future.

**I would suggest the following for WBCE 1.2.x:**
 1. copy theme fallback template files to /admin/theme/fallback/templates
 2. re-activate the theme template fallback in the WB class
 3. rework the entire stuff for WBCE 1.3.x or 2.x

**Comment by instantflorian** [comment]
+1 for that

**Comment by cwsoft** [comment]
Another option would be to move the entire AdvancedThemeWBFlat to /admin/theme/default and make it the default WBCE 1.2.x theme. One would need to make the Default Theme selectable in settings and prevent it from beeing deletet via Addons->Templates. The WB class can then be reactivated to use those files as fallback if a custom theme in templates does not provide the template file itself.

**Comment by NorHei** [comment]
I really was happy to have it outof the admin folder ... but i guss this time we keep it for compatibility ... 
Does the Theme work as fallback now , if you remove all other themes ?

**Comment by NorHei** [comment]
What Default theme you put into there ? I would vote for a basic Argos , Maybe an argos reloaded whithout the webfonts as it should have some refined page templates?

**Comment by instantflorian** [comment]
Take Argos reloaded (without webfonts) as we won't ship the old Argos 
any longer.

**Comment by NorHei** [comment]
Whats wrong whith it ?

**Comment by instantflorian** [comment]
Nothing in particular, but it's weird to ship a bunch of "Argos" backend 
themes, so in order to have at least one innovation which is visible 
also for non-professional users we should ship the reloaded Argos theme. 
I see no advantage if the old one still has to be maintained too.
See also
https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/232

**Comment by cwsoft** [comment]
Let it up to you to implement the final solution for 1.2.x.
