### ISSUE TITLE
Add help information for Sign-up selectfield

### ISSUE THREAD

**Issue by Colinax** [WBCE/WBCE_CMS#258]
![signup](https://cloud.githubusercontent.com/assets/22152866/25350421/5c2c13e6-2925-11e7-970d-d9d89a3b394e.jpg)

For better understanding why the Sign-up field is disabled we should add a help information field.

**Comment by instantflorian** [comment]
![signup](https://user-images.githubusercontent.com/1433754/29749494-9122f816-8b2d-11e7-856a-c1750f5475c2.png)
