### ISSUE TITLE
Wrong redirect by Error Messages

### ISSUE THREAD

**Issue by Colinax** [WBCE/WBCE_CMS#260]
When you click on Back at a Error Message it redirects to the Frontend, but it should stay in the Backend.

**Comment by instantflorian** [comment]
The problem appears at success messages too.

**Comment by NorHei** [comment]
Fresh install , cannot reproduce .. ??
Exactly what form i can find this?

**Comment by Colinax** [comment]
The wrong redirect by error & success messages are still present.

But only the Preferences and Addon sections are affected by this Bug

**Comment by instantflorian** [comment]
Seems to be fixed, I can't reproduce the error
