### ISSUE TITLE
Add JavaScript timer, to display end of session time

### ISSUE THREAD

**Issue by NorHei** [WBCE/WBCE_CMS#27]
Or maybe something else. 

At least we should set session livetime to an hour or so.

**Comment by instantflorian** [comment]
Oh yeah, that would be really great... *sigh*

**Comment by NorHei** [comment]
Adding such a timer is pretty easy.
Add this in header.htt

```
 <script type="text/javascript">
	setTimeout('alert(\'{TIMEOUT_WARNING}\')', {SESSION_TIMEOUT}*1000);
</script>
```

Problem starts when you work whith multiple tabs open and you use a tab relatively seldom , as the Counter does not know if you have prolonged the session by working on another tab. so the unused Window/Tab will throw its warning even if you are heavily working on other Windows/Tabs.

Any ideas?

**Comment by instantflorian** [comment]
maybe adding a checkbox "do NOT display a session time out warning in 
this window" to disable the function manually?
If possible, that checkbox could be pre-checked if the referrer of the 
tab belongs to the same wbce site - is there any way to check this?
e.g. working normally -> checkbox is not checked
ctrl-click on media to open media in new tab -> checkbox is checked due 
to "internal" referrer?


------ Originalnachricht ------
Von: "NorHei" <notifications@github.com>
An: "WBCE/WebsiteBaker_CommunityEdition" 
<WebsiteBaker_CommunityEdition@noreply.github.com>
Cc: "instantflorian" <info@meerwinck.com>
Gesendet: 02.09.2015 10:21:21
Betreff: Re: [WebsiteBaker_CommunityEdition] Add JavaScript timer, that 
gives a warning if session runs out while editing a page. (#27)

**Comment by NorHei** [comment]
right now i try to get around this using cookies

**Comment by NorHei** [comment]
Ok , cookies seem to work , as the new set one can prolong the time each time a page is loaded.
Now we need to make a decision. Do we alert just once on the window that triggers the warning first ?, or do we pop alerts in every window thats open. 

Right now this depends on garbage collection used by php , so  it may be that the session lasts longer  but i guess thats ok .

**Comment by NorHei** [comment]
Have no really good ideas on this right now  moved to Later

**Comment by Colinax** [comment]
Done with eaaaa341a36aade11b4a83257d1c9f70ffceb249
