### ISSUE TITLE
Remove blockquote style from AdvancedTheme

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#274]
The lines 696ff in the theme.css of the AdvancedFlat BE theme break the backend output of the GlobalComments tool and are afaik unnecessary anyway. So I think this can simply be removed:

`/* Zitatblöcke */
blockquote {
    position: relative;
    font-size: 28px;
    line-height: 48px;
    font-style: italic;
    margin: 60px 0 36px 50px;
    padding-left: 55px;
}
blockquote:before {
    display: block;
    position: absolute;
    content: "\201C";
    font-size: 4em;
    color: #303641;
    left: 0;
    top: 15px;
}`

**Comment by Colinax** [comment]
Yes, I remove it and other obsolete things too

**Comment by Colinax** [comment]
it's already done
