### ISSUE TITLE
Version 1.2.0. Die Bildgröße immer 100%. Stellt man im Wisiwig-Editor eine feste Höhe ein ist nach sichern die Größe wieder 100%. The Images size is not scalierable - after saving settign, like 100 pixel hight in Editor, it allways go back to 100%.

### ISSUE THREAD

**Issue by pixelhulk** [WBCE/WBCE_CMS#275]

**Comment by pixelhulk** [comment]
I Have just installed a clean System, all default! Not possible to change the size of an image.

**Comment by pixelhulk** [comment]
Remote and local is the same

**Comment by instantflorian** [comment]
Hi, it's not a bug, it's a feature. See WBCE Forum for Details:
https://forum.wbce.org/viewtopic.php?pid=10627#p10627
e.g. Remove the code block quoted in the forum post from module/ckeditor/ckeditor/config.js. The code was added to provide responsive images, e.g avoid that CKE adds hard-coded image size inline styles.

Btw. it would be great if you would use the description field of Github Issues too and do not place all the text only in the headline.

**Comment by pixelhulk** [comment]
Sehr geehrte Frau,
Sehr geehrter Herr,
Liebe Damen und Herren,

Many Thanks to you, and your Answer, 
yes it works know.

I am realy realy happy that Website Baker is live again - the Lepton thing was the wrong Way!
I grow up with WB, WB was my start in to CMS World, tell me if i can help.

yours jan p.






(0 64 05) 90 99 268
(01 76) 2 1108 266
Jan Petersen
Lindenstraße 18 - 35321 Laubach
jp@pixelpetersen.de
http://www.pixelpetersen.de <http://www.pixelpetersen.de/>
http://www.petersen-design <http://www.petersen-design/>.de










Am 30.05.2017 um 15:42 schrieb instantflorian <notifications@github.com>:

Hi, it's not a bug, it's a feature. See WBCE Forum for Details:
https://forum.wbce.org/viewtopic.php?pid=10627#p10627 <https://forum.wbce.org/viewtopic.php?pid=10627#p10627>
e.g. Remove the code block quoted in the forum post from module/ckeditor/ckeditor/config.js. The code was added to provide responsive images, e.g avoid that CKE adds hard-coded image size inline styles.

Btw. it would be great if you would use the description field of Github Issues too and do not place all the text only in the headline.
