### ISSUE TITLE
Version 1.2.0. No Code Window, like Version bevor - Sectoren (grüne Abschnitte) -  Code PHP Html etc 

### ISSUE THREAD

**Issue by pixelhulk** [WBCE/WBCE_CMS#276]
![new](https://cloud.githubusercontent.com/assets/14335915/26559605/ecfffac6-44b0-11e7-8d31-81c219b83812.png)
![alt](https://cloud.githubusercontent.com/assets/14335915/26559606/efe09d9a-44b0-11e7-9058-46c6808e5da0.png)

**Comment by instantflorian** [comment]
I can't reproduce this error. Is it a fresh installation or an updated one? Which version of code2 do you use?

**Comment by instantflorian** [comment]
No further information given by opener, so I'm closing this now
