### ISSUE TITLE
Bugs in droplets module

### ISSUE THREAD

**Issue by Colinax** [WBCE/WBCE_CMS#277]
In the droplet module for WBCE 1.x exists a "no Droplets Bug" when all droplets are deleted.

There is also a "Nothing selected bug", the droplets module creates a zip with no content (e.g.) by export if nothing is selected.

In addition, the bug fixes I created should also be checked for there correctness.

**Comment by NorHei** [comment]
Have You tried to use the one from DEV Branch (2.0)?
It has quite a few fixes and reworks as far as i remember.

**Comment by NorHei** [comment]
d67ba20
