### ISSUE TITLE
[1.3 alpha2] Page Tree not working

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#294]
Pagetree in BE is not displayed

Fatal error:  Uncaught Error: Call to a member function numRows() on null in /.../admin/pages/index.php:208 Stack trace: #0 {main}   thrown in /.../admin/pages/index.php on line 208
--

**Comment by NorHei** [comment]
Onmobile right now .. i am on it

**Comment by instantflorian** [comment]
found it: missing ' in line 207 after %page%

**Comment by instantflorian** [comment]
https://github.com/WBCE/WBCE_CMS/commit/9c8fab42b2b4aee032d9deeede3b64b23beb0f27
