### ISSUE TITLE
[1.3alpha2] OPF adds comments into sourcecode

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#296]
This is what the sourcecode looks like - see screenshot attached:
![opf](https://user-images.githubusercontent.com/1433754/29749285-60e9ae24-8b28-11e7-8fd9-d13d85a076c4.png)

Can this be disabled in a way?

**Comment by NorHei** [comment]
Sure , disable adding of placeholders in output filter settings . 

This does kill all capability of adding stuff to a certain place in template , as those places are no longer defined . 

Optionally you can make a filter, that removes them after they have been used. 
If you remind class Insert that used placeholders that became visible if not filtered correctly. 
This ones lo longer are visible for the user , the basic  concept is still almost the same. 

In Hortal placeholders are added manually in BE too , in Vertal they are added on automatic procedure. (If enabled)

Placeholders are needed so you can use simple not resource intensive replacement methods , and to have controll over what goes where if you want to have this controll. 

Another way would be to store page content in an array that contains all sub elements and compose the page at the end.  But thats no option for WBCE so far as it outputs everything directly.

**Comment by instantflorian** [comment]
Changing the setting for "Platzhalter Um Ziele zum Verschieben von JS, 
CSS und mehr zu haben:" to disabled has no impact.
To make sure I understand right: this <! -- META DESC+ -- > stuff is no 
debugging output but technically needed?

**Comment by instantflorian** [comment]
Sorry, posted in wromg issue the first attempt and deleted it without copying to the clipboard.

In short, I have understood the principe and I think I will get used to it.

**Comment by NorHei** [comment]
Have a little addition, you can disable all steps by putting a comment somewhere in the template.
This was meaned for debugging , but may be usefull for other purposes.   
''
Disables auto checking/setting of placeholders. 
''
Disables moving Stuff around. 
''
Disables replacements. 

so somewhere in the template:

Disables it completely. 

As i said , i may be an option to add a filter to remove this placeholders after they are needed. 
Optionally this filter should be capable of cleaning/minity the whole pagesource.
