### ISSUE TITLE
[1.3 alpha2] Undefined variable: breadcrumbs

### ISSUE THREAD

**Issue by Colinax** [WBCE/WBCE_CMS#297]
Notice: Undefined variable: breadcrumbs in C:\MAMP\htdocs\templates\wbce_hortal\index.php on line 299

This Notice is displayed in FE and only on startpage

**Comment by instantflorian** [comment]
I propose to change line 299 to
 <?php if (isset($breadcrumbs)) { echo $breadcrumbs; } ?>
