### ISSUE TITLE
[1.3 alpha2] Minify OPF disables pagetree in BE and causes some issues in FE

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#298]
With enabled minifier, the pagetree is not displayed
![filter_on](https://user-images.githubusercontent.com/1433754/29997136-e39cf2da-900b-11e7-9f0f-ebd645860af9.png)
Deactivating => everything ok
PHP 7.0.22, Firefox 55.0.3, Windows 8.1

**Comment by instantflorian** [comment]
...and in the frontend, the header image slider disappears

**Comment by instantflorian** [comment]
...and the default (photoswipe) and colorbox lightbox of RFG don't work.

**Comment by Colinax** [comment]
The problem is not the new minify filter but the scripts we use.

For example, this code line works fine:
`document.cookie = 'WBCELastConnectJS='+seconds.toString()+'; expires=0; path=/';`

This does not:
`document.cookie = 'WBCELastConnectJS='+seconds.toString()+'; expires=0; path=/'`

**Comment by instantflorian** [comment]
fixed with https://github.com/WBCE/WBCE_CMS/commit/ab2eec8ae434365a804e4bdb56d461a6e18a869c (filter removed)
