### ISSUE TITLE
File / Folder Permissions at Options are not saved

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#302]
Changed values are not saved, but remain to the old setting. I noticed that issue on different Linux/Unix servers.
![filesfolders](https://user-images.githubusercontent.com/1433754/31665796-625d1e40-b34a-11e7-9d20-59f5c09df2ed.png)

**Comment by BerndJM** [comment]
Can confirm it.
The reason seems to be: there are no (more?) "advanced options" in the server-settings.
But the save.php checks for $advanced (about line 65ff).
If one activate "advanced options" from another section in settings the values will be saved.

**Comment by BerndJM** [comment]
Attached the fixed settings.htt for the Argos-reloaded theme.
At the flat-theme I'll have a look tomorrow.
[settings.htt-argos.zip](https://github.com/WBCE/WBCE_CMS/files/1392783/settings.htt-argos.zip)

**Comment by BerndJM** [comment]
At least the fixed settings.htt for the Flat-theme
[settings.htt-flat.zip](https://github.com/WBCE/WBCE_CMS/files/1398970/settings.htt-flat.zip)
