### ISSUE TITLE
PHP Notice @Visitor Stats description

### ISSUE THREAD

**Issue by Tangol** [WBCE/WBCE_CMS#304]
Got this notice when checking the **Visitor statistics** module, on WBCE 1.3
![visitor_stats](https://user-images.githubusercontent.com/3336728/32149087-5e8fe406-bd08-11e7-8673-1e1d207329cc.png)

**Comment by Colinax** [comment]
Hi Tangol,

if I am not mistaken, the error comes from a variable that is not used in WBCE.

This variable is used to my knowledge in the latest version of WebsiteBaker. WBCE is a fork of WebsiteBaker so many modules can run on both systems and can cause some errors like this.

You can disable the error reports in Settings -> Show Advanced Options -> Disable PHP Error Reporting Level and select "Hide All Errors and Hints (www)".
