### ISSUE TITLE
Missing warning.html in BE-Theme causes fatal error

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#308]
When /templates/[current BE Theme}/templates/warning.html is missing, there is no backend access possible and only the following error ist displayed:

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'missing template file warning.html' in /homepages/.../framework/class.wb.php:508 Stack trace: #0 /homepages/.../admin/login/index.php(42): wb->correct_theme_source('warning.html') #1 {main} thrown in /homepages/.../framework/class.wb.php on line 508

The error appears always, no matter if the warning should have been displayed or not.

I think a missing rather unimportant file should not crash the whole system, so in my opinion we need to fix this.

**Comment by Colinax** [comment]
To fix this, we need to solve #249 or we decide to move the, currently missing, internal warning.html to admin/login.
