### ISSUE TITLE
Security patch for 1.1 / 1.2 creates wrong table name

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#319]
The session data is stored in a table literally called {TP}dbsessions, e.g. the placeholder for TablePrefix is not replaced by the real prefix. This might cause problems on some servers (e.g. login to the backend does not work.)

**Comment by instantflorian** [comment]
A bugfix should remove or rename the wrong table.
Furthermore it needs to be checked how to avoid that this table gets too large.

I think this table has to be removed when updating to 1.3.x so the update script has to be changed too.

**Comment by instantflorian** [comment]
Problem solved, class.database.php has to be updated with the file from 1.3 too. I've added the file into the patch. 
Nevertheless the update script for 1.4 should remove the wrong table.

**Comment by Colinax** [comment]
365200d
