### ISSUE TITLE
Installer sets always http, also when called from https

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#320]
The installer suggests always htt**p:**//domain.tld for WB_URL, even if http**s**://domain.tld is available resp. the installer is called from http**s**://domain.tld. This leads to a wrong URL in the config.php; so when https is forced by htaccess, the whole site looks broken, because all backend/frontend stylesheets and scripts are not loaded.

**Comment by instantflorian** [comment]
Furthermore: if WBCE just has been copied onto the server, the redirect from the /index.php to /install/index.php sets the host to http (instead of staying at https)

**Comment by Colinax** [comment]
fixed with 532d5841c8b1283858f5fab61d1407b856b9a115 and bcbecf51d83518cde7dc558349be5495b1206bd9
