### ISSUE TITLE
Settings table for SEO tool is missing

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#321]
In some cases the table mod_page_seo_tool is missing after updating to 1.3.x, so the tool does not work properly (display errors) and settings can not be stored. It's a bit strange, I don't know why/how the table is removed.

**Comment by Colinax** [comment]
Is it possible to check the error.log of the DB?
In some (rare) cases it happens that the DB can't read the sql entries and mark them as broken.
