### ISSUE TITLE
Unnecessary elements shown in droplet tool

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#323]
The red marked elements should not appear in the droplet edit mode.
The error appears since 1.3.1 afaik, probably an issue with TWIG.
![2018-01-22_092117](https://user-images.githubusercontent.com/1433754/35211351-610ce6f8-ff56-11e7-97be-2448bc6d77a8.jpg)

**Comment by Colinax** [comment]
This behavior is the result of the fix for the "No Droplet" bug.

The problem is in the tool.twig file d67ba20d6acd6ca6584880eccb61bbec6811ad39
