### ISSUE TITLE
Update / security announcements in the backend

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#325]
There should be a simple way to show important update or security hints in the dashboard. The trigger can be a PHP file on wbce.org, the RSS feed of the announcement thread in the forum, whatsoever. 
This could possibly be done just like the way the backend displays a warning when the install directory still exists, a simple sentence with a link, nothing more, nothing less.

**Comment by digitalbricks** [comment]
Yes, that would be a great improvement!
Also a simple check for a newer WBCE version should be implemented, wich appropriate notification is also shown to editors with minor rights (so they could contact their administrator).
