### ISSUE TITLE
Better/Other brute force protection

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#326]
The  switch to the static "access denied" page after too many wrong login attempts should be replaced, since many users can't handle this and do not know how to re-activate the login screen.
Some ideas:
- the short login delay from 2.0 DEV (maybe with an exponential rising time, the more failed logins, the longer the delay)
- beneath username and password a mandatory captcha (but please not this annoying Google "mark every field with cars / traffic signs etc. for the rest of your life"  stuff)
- optional report mail to the administrator or a given mail address, and/or a logfile to report login attempts
- user account is deactivated and has to be reactivated by admin after too many attempts

**Comment by mrbaseman** [comment]
I have implemented the variant with an exponential rising time in https://github.com/WBCE/WBCE_CMS/commit/4e44c753158aa064b603263c6ff2aab3f8997ae1
