### ISSUE TITLE
PHP 7.2 Compatibility

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#335]
When running under PHP 7.2, the following notices appear:

Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /.../framework/class.login.php on line 35
und im Frontend:
Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /.../include/phplib/template.inc on line 407

So we should have a look on this, maybe there are other issues caused by the latest PHP version.

**Comment by Colinax** [comment]
it's already fixed 1c6fe13f973f9f1cc66bb6e2bb344c5c5e345f89, 7b717b8256e9a866fa9d5814f5582dc69ee6d99f and 3deeff21a8be183057cfcb8141f35471e6fdf650

**Comment by instantflorian** [comment]
D'oh! I'm sorry.
