### ISSUE TITLE
little issue with deprecated each() function in lass.login.php on line 35

### ISSUE THREAD

**Issue by WebDesignWorx** [WBCE/WBCE_CMS#338]
I just got this issue with PHP > 7.1

`Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /users/steftest/www/wbce_131/framework/class.login.php on line 35`

To handle just replace the line:
-  while (list($key, $value) = each($config_array)) {
with
+ foreach ($config_array as $key => $value) {

Regards, 
Christian

**Comment by Colinax** [comment]
This is alredy fixed since Feb 13, 2018. #330
