### ISSUE TITLE
Installer accepts too many kinds of characters for admin password

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#343]
When installing WBCE from the scratch it is possible to create an admin password including characters which would be rejected as invalid in the backend. That means, you can initially create a password with for example a " (double quote) inside, but using this character in a password entered in the settings dialogue or when creating a new account won't be possible.
So either the installer has to be fixed to accept only the number of special characters as allowed by the framework, or the framework has to be openend for all kinds of special characters in the password.

**Comment by Colinax** [comment]
With the commit above, the wrong behavior is fixed
