### ISSUE TITLE
Create an optional Output Filter for Security Headers

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#344]
See https://forum.wbce.org/viewtopic.php?pid=19709#p19709

Please note: in case this filter will be added, it should not be activated by default.

**Comment by mrbaseman** [comment]
@instantflorian How shall the html header code look like, which the filter is supposed to insert? Is it already clear? If yes, could you paste it here, please?

**Comment by instantflorian** [comment]
`<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'">
<meta http-equiv="X-Content-Security-Policy" content="default-src 'self'; script-src 'self'">
<meta http-equiv="X-WebKit-CSP" content="default-src 'self'; script-src 'self'">`
But then no inline-JS will be executed any longer, so there has to be added
`<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline'">
<meta http-equiv="X-Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline'">
<meta http-equiv="X-WebKit-CSP" content="default-src 'self'; script-src 'self' 'unsafe-inline'">`
what might make the headers useless, so I don't know. see the forum thread for details.

**Comment by mrbaseman** [comment]
I didn't capture a consensus from the forum thread, that's why I was asking here. I can also imagine a configurable filter, which allows to switch on/off each line separately, and with/without 'unsafe-inline'.
OpF Dashboard already supports filters with such a flexibility, and one can easily develop and test them there. I'll put it on my list, and maybe this becomes another item on the "advanced features agenda" that becomes possible with OpF... Or, once we have experience with testing there, we can backport it to 1.3.x (inactive by default, then).

**Comment by mrbaseman** [comment]
I have posted a first draft with OpF dashboard [in the forum](https://forum.wbce.org/viewtopic.php?pid=19859#p19859). It relies on `Auto Placeholder` - so it needs to be moved up before `Remove System PH`, and those two have to be activated. This could be done automatically during installation, but I forgot to implement this. I'll publish an improved version.
Anyhow, included is a filter.php file which could also serve as a template for a classical output filter - if anyone wants to implement it the traditional way. The nice thing with the OpF Dashboard is that the backend is already there and just a few lines of code are sufficient to implement a quite flexible plugin filter...

**Comment by instantflorian** [comment]
Filter is available for download in AOR
https://addons.wbce.org/modules/download_gallery/dlc.php?file=32&id=1542361689&sid=20

**Comment by mrbaseman** [comment]
I forgot to mention here that this is the improved version of the filter which moves to the right position during installation and switches on its dependencies if not already activated. Note that this works with the filter modules and the latest version of the OpF Dashboard (which I have released yesterday). This version and the filter modules have been merged into the master branch of WBCE with #345 as you can see above.
