### ISSUE TITLE
Obsolete files were not obsolete

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#366]
#365 causes errors when creating a new menu link:
Warning: include(/.../modules/menu_link/wb_dump.function.php): failed to open stream: No such file or directory in /.../modules/menu_link/modify.php on line 26

Warning: include(/.../modules/menu_link/wb_dump.function.php): failed to open stream: No such file or directory in /.../modules/menu_link/modify.php on line 26

Warning: include(): Failed opening '/.../modules/menu_link/wb_dump.function.php' for inclusion (include_path='.:/opt/php/7.1.23/share/pear') in /.../modules/menu_link/modify.php on line 26

**Comment by Colinax** [comment]
fixed in 8e9007b5e25b54a52b84cacb6236bf9370136b8d
