### ISSUE TITLE
use I/Insert class throughout the code base

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/WBCE_CMS#376]
Meta tags, Keywords, Javascript, CSS style should not be inserted directly by core functions or the template. Generally, it is better to use the mechanisms of the I/Insert class throughout the code, so that it can order/replace the code parts that are in its internal queues. 

See [this commment in #373](https://github.com/WBCE/WBCE_CMS/pull/373#issuecomment-456406379) and [that one](https://github.com/WBCE/WBCE_CMS/pull/373#issuecomment-456584607)

(#373 which addresses the most urgent hotspots has been merged already into master)

**Comment by Colinax** [comment]
fixed with #382
