### ISSUE TITLE
Wrong page visibility icons in WBCE Flat Theme

### ISSUE THREAD

**Issue by digitalbricks** [WBCE/WBCE_CMS#380]
When using the WBCE Flat Theme the pages overview page shows wrong icons for visibility "Hidden" and "Private": Pages with the visibility "Hidden" are shown with the lock icon, pages with the visibility "Private" are shown with a crossed eye icon – see attached screenshots.

This issue is only present in WBCE Flat Theme, not in Algo Reloaded Theme (wich also uses da different icon for hidden pages – the "trenchcoat agent" icon).

![bildschirmfoto 2019-02-04 um 13 53 19](https://user-images.githubusercontent.com/2983578/52209878-8c3bc700-2885-11e9-9329-fb9424550dc5.png)
![bildschirmfoto 2019-02-04 um 13 52 59](https://user-images.githubusercontent.com/2983578/52209879-8c3bc700-2885-11e9-874d-3844079e8aa4.png)

**Comment by digitalbricks** [comment]
I corrected the wrong icons in my recent project and want to share the needed changes:

**File: `/templates/wbce_flat_theme/patch/functions/renderPageTree.php`, Lines 84-98, BEFORE**

```php
<td class="visibility">
    <?php if ($page['visibility'] === 'public') { ?>
        <i class="fa fa-eye"></i>
    <?php } else if ($page['visibility'] === 'private') { ?>
        <i class="fa fa-eye-slash"></i>
    <?php } else if ($page['visibility'] === 'registered') { ?>
        <i class="fa fa-key"></i>
    <?php } else if ($page['visibility'] === 'hidden') { ?>
        <i class="fa fa-lock"></i>
    <?php } else if ($page['visibility'] === 'deleted') { ?>
        <i class="fa fa-trash-o"></i>
    <?php } else { ?>
        <i class="fa fa-ban"></i>
    <?php } ?>
</td>
```

**File: `/templates/wbce_flat_theme/patch/functions/renderPageTree.php`, Lines 84-98, AFTER**

```php
<td class="visibility">
    <?php if ($page['visibility'] === 'public') { ?>
        <i class="fa fa-eye"></i>
    <?php } else if ($page['visibility'] === 'private') { ?>
        <i class="fa fa-lock"></i>
    <?php } else if ($page['visibility'] === 'registered') { ?>
        <i class="fa fa-key"></i>
    <?php } else if ($page['visibility'] === 'hidden') { ?>
        <i class="fa fa-eye-slash"></i>
    <?php } else if ($page['visibility'] === 'deleted') { ?>
        <i class="fa fa-trash-o"></i>
    <?php } else { ?>
        <i class="fa fa-ban"></i>
    <?php } ?>
</td>
```

(assigned `fa-lock` to visibility `private` and `fa-eye-slash` to visibility `hidden`)

This fixed the described issue. **But** I also found such a icon asignment in `/templates/wbce_flat_theme/patch/page_tree.php`. There it is for displaying the legend below the page tree and so the icons assignment should be changed there also like mentioned above.

**Comment by Colinax** [comment]
This is no Issue please read the Descriptions (below the pagetree), for more please visit our forum.

**Comment by digitalbricks** [comment]
@Colinax You mean, because the legend below the page tree **also** shows the wrong icons, this is no issue? Ok, for sure this is no php development issue but a graphical one. A lock icon symbolizes always something that is locked (and could maybe unlocked). But this is not true for pages set to `visibility:hidden` – but it's true vor pages with `visibility:private`. On the other hand, a page with slashed-eye-icon does not symbolize a page which is some kind of locked. 

So a **in this case** i do not agree with you. Wrong visual identifiers don't become correct just by repeating them in a description – such as the legend.
