### ISSUE TITLE
Installer und update Skript nochmal überarbeiten

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/WBCE_CMS#392]
Mir fällt gerade noch eine ältere Mail in die Hände, in der ich gebeten wurde ein Issue zu diesem Thema aufzumachen. Da gerade mehrere Themen bearbeitet und gemerged werden, dürfen wir die beiden "Sonderlocken" vor dem nächsten Release nicht vernachlässigen:

Im update-Skript muss wahrscheinlich die Liste der in der Zwischenzeit gelöschten Dateien nochmal überarbeitet werden (am einfachsten durch Vergleich des master mit dem 1.3-Branch kurz bevor das 1.4-er Release in den Betatest geht) - und man sollte von ein paar gängigen Umgebungen das Update direkt auf 1.4 testen.

Installer: vergisst man gerne, ist aber auch so eine Sonder-Umgebung wie das update-Skript und sollte zumindest vor dem Aufruf mal durchgetestet werden.

**Comment by mrbaseman** [comment]
Bei der Gelegenheit: Ausmisten von Dateien, die gar nicht (mehr) verwendet werden, z.B. Klassen, die nirgends in Verwendung sind

**Comment by instantflorian** [comment]
Wenn der Installer irrtümlich bei einer bestehenden Installation (z.B. Update) aufgerufen wird (anstatt der Update.php), führt das Anklicken des "Check your Settings in Step 1"-Buttons auf eine Fehlerseite in s/w:
https://forum.wbce.org/viewtopic.php?pid=23896#p23896
Abhilfe: Check Your Settings nicht als Button bzw. nicht als Aufruf der save.php sondern Reload der install/index.php

**Comment by Colinax** [comment]
Die deprecated or removed file Liste ist aktuell und das komische Check your Settings Verhalten wurde ebenfalls korrigiert.

Daher sage isch mal closed
