### ISSUE TITLE
Notices on Login Screen

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#401]
Fresh install from master (date 2019/03/23, 22:11)

If PHP notices are enabled, on the backend login screen and also the frontend login appears

Notice: Undefined property: Login::$time_frame in /.../framework/class.login.php on line 303
Notice: Undefined property: Login::$time_frame in /.../framework/class.login.php on line 314

**Comment by mrbaseman** [comment]
the name of the property was without underscore, so when using it one should spell it correctly.
$timeframe is an additional delay of 10 minutes:
```
admin/login/index.php:                                          'TIMEFRAME' => "600",
account/login.php:      "TIMEFRAME"             => "600",
```
Since there is already a delay it's not that important. It becomes more relevant the smaller the values for MAX_ATTEMPTS and LOGIN_DELAY are chosen.
