### ISSUE TITLE
Accessfiles of deleted / not visible pages

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#405]
If a page is set to visibility: none or put into the wastebin, the accessfile (the small .php file in the /pages folder) is still existing. Calling the URL of a deleted/invisible page displays an ugly page in the current page design but a message "Sorry, no active content to display" in each block.

I would prefer that the accessfile of a not visible or deleted page is removed, so outdated bookmarks/links would lead to the 404 page of the website instead of showing confusing content. 
When restoring/republishing such a page, its accessfile has to be re-created of course.

Since other people might not prefer this, this could be configured by a new setting in the config.php, e.g. REMOVE_INVALID_ACCESSFILES or sth. like this.

**Comment by WebDesignWorx** [comment]
Just a suggestion: wouldn't it be better to use....
`// page moved temporarily
header('Location: http://www.yoursite.com', true, 302);
exit;`
... within the access file, instead of deleating it completely?
Just making sure Google et al keep checking in with the URL of said page?

**Comment by instantflorian** [comment]
Well, good point.
But what's with the "human users", which might be puzzled when finding themselves on the startpage? Maybe the target page can be defined in the config.php, so that the admin can define the page which should be displayed (i.e. the 404 page or a "currently unavailable" page)?

**Comment by WebDesignWorx** [comment]
I thought about the feature of having a option to set where the 302 should redirect to, but that's a bit complicated for this release (not that it can't be done, it's just some more sophistication and many files involved - including theme files).

So, OK, I will stick with the initial idea and just deleate the access file.

**Comment by instantflorian** [comment]
Solved with https://github.com/WBCE/WBCE_CMS/commit/239e11356daf5b2e5e04a39d0213f243bb936786
