### ISSUE TITLE
Send password failure

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#408]
On login, when clicking on "Forgot password" and submitting the (correct) email adress to send new credentials, no mail is sent. Instead, one is redirected to (URL)/account/signup_continue_page.php?switch=wrong_inputs.

**Comment by WebDesignWorx** [comment]
OK, will have a look.

**Comment by instantflorian** [comment]
Additional infos: 
- Tried to login /send PW from backend, e.g. (URL)/admin/login/forgot/index.php. 
- Website is in maintainance mode.

**Comment by WebDesignWorx** [comment]
OK, I have found the issue and will make a PR shortly.
