### ISSUE TITLE
jqueri-ui-datepicker missing language file

### ISSUE THREAD

**Issue by BerndJM** [WBCE/WBCE_CMS#415]
The one-for-all module relys for the start/end-date functionality in the first place on the jquery-ui-datepicker language files taking the language shortcut from "LANGUAGE".
The -en file is missing so there occur the funniest results in the start/end-date handling.

Solution:
In  `/include/jquery/i18n/` just make a copy of `jquery.ui.datepicker-en-GB.js` as `jquery.ui.datepicker-en.js`
And I think the dateFormat in the new file should be changed to 'mm/dd/yy'
the original 'dd/mm/yy' is not the format we really want for an en-file...

See also:
https://forum.wbce.org/viewtopic.php?pid=23700#p23700

**Comment by instantflorian** [comment]
This is merely an issue of the module, not the core. I think it's better to fix it in the module.
The standard i18n package does not contain the named file by default.
https://github.com/jquery/jquery-ui/tree/master/ui/i18n

**Comment by BerndJM** [comment]
You're right, I will try to fix this in the module.
I think to rewrite an detected language "en" to "en-GB" would be the easiest way.
And additional will add a fallback for missing language files which than defaults to "en-GB"

**Comment by BerndJM** [comment]
Fixed it.
The save_items.php now has the same fallback values as normaly (in the entry form) are provided by the datepicker core file.
