### ISSUE TITLE
problematisches Verhalten bei require_once

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/WBCE_CMS#417]
wir haben irgendwo mal die [hier beschriebene](https://github.com/WBCE/News-with-Images/issues/24#issuecomment-487427039) Änderung diskutiert aber die Auswirkug auf require_once nicht bedacht. Die Block-Inhalte jeweils separat in einem Funktionsaufruf anstatt in einer fotlaufenden Schleife zu generieren hat erwünschte Effekte (weniger Kollisionsfläche für Variablen die von Modulen verwendet werden), aber auch unerwünschte Effekte (requiere_once funktioniert nicht so wie man es erwarten würde)

**Comment by mrbaseman** [comment]
Hier der Link zur erwähnten Diskussion https://forum.wbce.org/viewtopic.php?id=2742

**Comment by WebDesignWorx** [comment]
Bitte Beispiel anfügen, wo das/die Probleme mit require_once auftreten.

**Comment by instantflorian** [comment]
https://github.com/WBCE/News-with-Images/issues/24

**Comment by mrbaseman** [comment]
Man nehme ein Modul, das in der view.php die Sprachdatei per require_once einbindet und daraus eine  Variable für den Output im Frontend verwendet. Davon setzt man zwei gleiche Sections untereinander. Dann ist die Variable in der zweiten Section nicht gesetzt. Tauscht man die Sections, ist wieder die zweite betroffen, die vor dem Tausch funktioniert hat.

**Comment by mrbaseman** [comment]
ich habe mit diversen Modulen rumgespielt. Die Problematik, dass Sprachvariablen teilweise nicht definiert sind, kommt bei einigen vor, ein Beispiel davon ist auch das "helloworld", was nicht mehr richtig funktioniert, wenn es zweimal auf der gleichen Seite aufgerufen wird. miniform und minigallery sind zwei Kandidaten, die nicht nur Sprachdateien sondern auch Funktionen in der view.php einbinden, aber die funktionieren einwandfrei.
Ich habe das auch in helloworld mal nachgestellt und explizit in view.php die Zeilen
```
require_once(WB_PATH .'/modules/helloworld/funktionen.php');
helloworld_funktion();
```
eingebaut und in der bewusst nicht als fuctions.php benannten, hier eingebundenen Datei:
```
<?php
function helloworld_funktion(){
        echo "helloworld_funktion() has been called\n";
}
```
Die Ausgabe erscheint seltsamerweise bei beiden Sections. Also bleibt die Funktion nach dem ersten Laden erhalten, Variablen, die in der eingebundenen Datei gesetzt werden, werden aber zwischen den beiden Durchläufen verworfen.
Damit die Sprachvariablen für den zweiten Durchlauf auch geladen werden, muss man eben require_once durch require ersetzen. Das ist keine schwere Aufgabe, es betrifft nur Module, die von sich aus Text fürs Frontend mitbringen - es geht nicht um Text der sowieso aus der DB kommt, und das Problem hat man auch nur, wenn zwei gleichartige Sections auf der gleichen Seite sind. 
Da werden sicher Hilferufe kommen, wenn wir das Verhalten so lassen, wie es im Moment implementiert ist, aber der Aufwand scheint mir jetzt nach eingehender Betrachtung doch überschaubar.
Ach ja, und Fazit aus dem [oben](https://github.com/WBCE/WBCE_CMS/issues/417#issuecomment-487460257) verlinkten Thread: Um bewusst Variablen von einer Section an die nächste zu übergeben (z.B. mehrere Code/Code2 Sections) müssen sie in beiden Sections als global deklariert werden. Bisher wurden einmal gesetzte Variablen beibehalten, was in nachfolgenden Sections zu unerwünschten Effekten führen könnte, was aber vielleicht auch manche (bewusst oder unbewusst) ausgenutzt haben. 
Dass man das geradezieht ist sicher richtig und mal schauen, was in der Betatestphase dann so reinkommt. Dann können wir immer noch entscheiden, ob wir hier noch was ändern müssen oder ob ggf. Module angepasst werden sollten. 
Es ist auch gut, dass solche Effekte schon entdeckt werden, bevor eine Beta fertig ist. Dann sind wir vorbereitet und können schnell Hilfestellung leisten oder noch besser man kündigt es als bewusste Änderung an und weist von vorne herein darauf hin, dass hierfür ggf. kleine Anpassungen in den Modulen erforderlich sind.

**Comment by instantflorian** [comment]
Meine Antwort im Forum (interner Bereich, aus Gründen™)
https://forum.wbce.org/viewtopic.php?pid=23944#p23944
