### ISSUE TITLE
Feature request: Send HTTP status code 404 for pages with visibility none

### ISSUE THREAD

**Issue by digitalbricks** [WBCE/WBCE_CMS#419]
## Feature request:
Pages with the visiblity set to `none` should return a HTTP status code 404 ("Not Found") instead of displaying an empty page with an error message (in german: "Sie haben keine Leserechte für diese Inhalte") and HTTP status code 200 ("OK").

## Why this is usefull:
Because pages with visibility set to `none` are intented to be no longer accessible, the status code 200 sends the (conceptual) wrong signal to the clients and causes search engines to keep this pages in the index. But as non-visible pages do not have any value for a user, they should be removed from the search engine index and also users who had the URL in their bookmarks should be informed that these pages are no longer accessible. Sending a 404 instead a 200 status code would be the "right" way to handle requests to such URLs. And while using a 404 status code, we could use the `ErrorDocument` rule in the `.htaccess` to show a custom 404-page.

## Addition
The 404 status could be also returned for pages with visibility set to `private` or `registered` when the user is not logged in or has no access rights. This would prevent "hammering" a site for non-public pages by guessing/testing URLs. Because sometimes the URL alone already gives some information about the page contents (eg. `/pages/secret-new-product-launches-oct2019.php`). So letting the server say "nothing to see here, move along" would be better than "here is something but you are not allowed to see".

**Comment by Colinax** [comment]
Hi digitalbricks,

this feature ist allready in the master branch, see the changes from April 13, 2019 https://github.com/WBCE/WBCE_CMS/commits/master

**Comment by digitalbricks** [comment]
Ah great!

But, just for understanding: It seems that this is accomplished for pages with visibility `none` by deleting the access file? So this solution could not be adapted to pages with visibility `private` or `registered`, isn't it?

Would it not be more convenient to use `http_response_code(404)` or `header("Status: 404 Not Found")` for PHP<5.4? 
Well, sending the status code via PHP can only be done before the first byte is sent to the client, so the page visiblity has to be checked on a earliest possible stage before rendering any HTML. Maybe that could be problem - I am not such deep in the working of the WBCE core.

**Comment by Colinax** [comment]
The current master and the next WBCE 1.4 release require php 5.6 or higher.

**Comment by digitalbricks** [comment]
All the better – so `http_response_code(404)` could be used definitely (if the WBCE core is capable of determining the page visibility setting and the user rights before the first byte is sent to the client)

**Comment by Colinax** [comment]
I am not a core developer, please visit our forum to continue the topic

**Comment by instantflorian** [comment]
Reopened due to
> So this solution could not be adapted to pages with visibility private or registered, isn't it?
you're all welcoe to discuss the feature here and/or propose solutions.

**Comment by digitalbricks** [comment]
As you suggested, i moved this discussion to the forum: [https://forum.wbce.org/viewtopic.php?id=2795](https://forum.wbce.org/viewtopic.php?id=2795).
There is also a working code example for returning the 404 in the `index.php` of WBCE.

**Comment by instantflorian** [comment]
This is still not working.

**Comment by WebDesignWorx** [comment]
What exactly is missing here? Or needed/wanted?
As far as I see, the linked forum thread says it was resolved:
https://forum.wbce.org/viewtopic.php?pid=24020#p24020

**Comment by instantflorian** [comment]
It's not, unfortunately. It works for pages in "deleted" state, but not for pages with "visbility: none", where still a page as following appears in the frontend when calling the URL of the page.
![2019-11-24_145258](https://user-images.githubusercontent.com/1433754/69515704-b9aa4c00-0f4f-11ea-97be-73dd8c2dfd62.jpg)

**Comment by WebDesignWorx** [comment]
Do you have a link to the original commit?
Can't seem to find it in the history.

**Comment by instantflorian** [comment]
https://github.com/WBCE/WBCE_CMS/commit/239e11356daf5b2e5e04a39d0213f243bb936786

**Comment by WebDesignWorx** [comment]
OK, the above changes should do.
The access file will be deleted when page visibility is changed to 'none'.
Also, the access file will be not generated, when a newly created page is set to visibility  'none' .

**Comment by WebDesignWorx** [comment]
Does it work for you guys?

**Comment by instantflorian** [comment]
It does. thx.

**Comment by instantflorian** [comment]
The changes are not available in the 1.4.1/development branch yet (because as far a I can see there are also changes related to PDO/new function names). So I reopen this issue. If possible, it would be nice if just the 404 / access file behaviour could be changed in the development branch too.

**Comment by instantflorian** [comment]
Sorry, but this does not work properly yet. It works for pages in the root, but not for pages on lower levels.
That means, in a structure like
page 
-- subpage of page 
etc.
page: accessfile ist deleted as wanted/expected
subpage: accessfile is not deleted (also not if the parent page is set to invisible/deleted)

**Comment by WebDesignWorx** [comment]
OK, I will have another look at it.

**Comment by instantflorian** [comment]
This still does not work. I guess the issue was closed unintentionally.

**Comment by instantflorian** [comment]
Finally, hopefully , solved.
