### ISSUE TITLE
Sending Login credentials via backend login screen fails

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#422]
When clicking on "Forgot password" on /admin/login and entering a valid email address, WBCE claims to have sent an email. But actually **no** email is sent.

The issue does not appear when clicking on the Forgot password link in the frontend (account/login).

**Comment by instantflorian** [comment]
Sorry, I was mistaken. It just took half an hour to deliver the mail...

**Comment by mrbaseman** [comment]
sounds like a greylisting configuration on the mail server

**Comment by instantflorian** [comment]
Yes, seems so. Strange: The mail which was generated by the frontend form, which differs in wording only a little bit, was not greylisted and delivered immediately. That's why I thought the other password forgotten mail would not work (but also because I had a similiar request by a customer).

**Comment by mrbaseman** [comment]
usually, the second attempt (even if it is a different mail) passes such a filter quickly. I have often observed similar issues when registering for an online service. The first mail with the confirmation link gets stuck in the greylisting, but when I click on a "resend email" button, the second mail passes immediately, and the first one arrives later when the email server re-tries to deliver it after some grace period
