### ISSUE TITLE
improve media management

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/WBCE_CMS#423]
as [discussed e.g. in the context of News with Images](https://github.com/WBCE/News-with-Images/issues/29#issuecomment-491212617) it would be good to have a better interface for the upload of media, i.e. something that supports Drag&Drop, uploading multiple files with one control element rather than with an individual input field for each file, parallel upload in the background...
There is more room for improvement in the current media management, but at least a more convenient upload mechanism would be a big step forward.
For News with Images we use the [jQUery Ajax File Uploader](https://github.com/danielm/uploader), a modern, small, but nevertheless widely configurable solution. It requires a bit of adaption to be integrated into the core, but it's feasible and adds a notable benefit of the upcoming release for the end user.

**Comment by Colinax** [comment]
fixed with 7ec1f2d85b638e20585b4db3b0119fc87764bd64
