### ISSUE TITLE
Last update of a page is not reliable

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#430]
The "last update" information is incorrect if there are no wysiwyg sections (for example only miniform or sth. else) on the page.
The last update information is not updated even if settings of the page are changed.
![2019-07-03_130340](https://user-images.githubusercontent.com/1433754/60586823-2fd8c700-9d93-11e9-883a-1cbf3ed833d5.jpg)

**Comment by Colinax** [comment]
I can confirm this bug, but it only occurs on modules without a save button.
If this happens it will display the creation time instead of last modified (checked with a newly created site)

**Comment by webbird** [comment]
Modules supporting the last modified date set $update_when_modified to true. If there is no such module on a page, the last modified date will never be updated.

**Comment by instantflorian** [comment]
This is quite strange, because miniform *has* a save button, /miniform/save.php is executed and in the save.php is also the line $update_when_modified = true; - so I don't see why the last update information is not changed.

When changing the page settings, the update date of the page is never changed, I'm not sure if this is intended and useful. I tried adding the $update_when_modified = true; to /admin/settings2.php, but that does not help.

**Comment by Colinax** [comment]
i think that the function in modules/admin.php#L191 is broken

see https://forum.wbce.org/viewtopic.php?pid=25090#p25090

**Comment by instantflorian** [comment]
Error does not appear with other modules (wysiwyg, code2, menulink, topics, mpform, sitemap) - but the error appears also with minigallery (and minigal has a asave button on its settings panel)

**Comment by Colinax** [comment]
Could it be that there are some incompatibilities between WBCE and WB (that is, our modules are working properly, cross-CMS modules like minigal not)?

**Comment by instantflorian** [comment]
I don't think thats the reason, since other cross CMS modules like code2, mpform or bootstrap multiple columns do not show that error.

**Comment by instantflorian** [comment]
https://github.com/WBCE/WBCE_CMS/commit/8c08e97c509636e4c69553a6a238baf9ce06567a
