### ISSUE TITLE
Warning on login screen

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#436]
Update from 1.3.3 to 1.4 RC
/admin/login 
Warning: Use of undefined constant ADMIN_DIRECTORY - assumed 'ADMIN_DIRECTORY' (this will throw an Error in a future version of PHP) in /.../framework/initialize.php on line 75

**Comment by instantflorian** [comment]
The error appears if ADMIN_DIRECTORY is not defined in the config.php, so it can be fixed by adding that line; nevertheless it's odd, because this issue does not appear with WBCE <1.4

**Comment by WebDesignWorx** [comment]
I see, please move the marked lines below where the constants are defined (what is now L84)
https://github.com/WBCE/WBCE_CMS/blob/master/wbce/framework/initialize.php#L74-L77

**Comment by instantflorian** [comment]
https://github.com/WBCE/WBCE_CMS/commit/502f4c2e59bbc19fae870aca6a6fdcbe90de5506
