### ISSUE TITLE
Activate OPF Cache Control for Backend pages and search results by default

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#437]
This is not the case yet (tested on fresh installations and updates)

**Comment by WebDesignWorx** [comment]
In backend the filemtime strings are always applied and attached to the js|css files (by design).

I will have to have a look at the search results though.

**Comment by instantflorian** [comment]
No, that's not the case unfortunately, otherwise I would not stumble into display errors like this.
![2019-07-15_185615](https://user-images.githubusercontent.com/1433754/61234056-64a13280-a732-11e9-9905-8da7ea80c591.jpg)
See source code:
![2019-07-15_185643](https://user-images.githubusercontent.com/1433754/61234049-61a64200-a732-11e9-8f39-baab23f360ce.jpg)

**Comment by WebDesignWorx** [comment]
Ah, OK.
I see.
These are the files that are linked from within the template, not the Insert Class.
In this case, @mrbaseman should have a faster clue on what to do.

**Comment by mrbaseman** [comment]
This one is not (yet) automatically activated for search results. I can update this later today. It should be active for the backend though. If it's not we have to check the order of filters in the page (last) category. Cachecontrol is a plugin, not a module and it's Independent of the insert class, and hopefully after the insert filter. I will have a look

**Comment by mrbaseman** [comment]
fixed with commit https://github.com/WBCE/WBCE_CMS/commit/4d31039b32a0619fd985c66fd21eab45995a4fc8

two things to note: 
as I have posted already before, searchresults were not activated by default, and secondly, for the backend I have added the string 'backend' to the wrong option in the install routine. Sorry.

**Comment by instantflorian** [comment]
works fine now.
