### ISSUE TITLE
Parent Page selection not working

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#441]
![2019-07-22_113854](https://user-images.githubusercontent.com/1433754/61622582-5c3a8180-ac75-11e9-8155-e66385f766b9.jpg)
The selection of a parent page in the new page dialogue does not work properly. Whether a page is selected from the pulldown manually, or the desired parent page is slected from the page tree, the new page is always created in the root - but oddly as a "neighbour" of the page which should have been the parent page, not at the end of the list as usual when Parent: None" is selected.

Changing the parent page of an existing page via the page setting works fine.

The error appears both in Argos and Flat BE theme. 
WBCE 1.4 RC2, PHP 7.3

**Comment by instantflorian** [comment]
As far as I can see this error came with this commit
https://github.com/WBCE/WBCE_CMS/commit/7cf8533ed254a7a66e2eb2fb6b96752da8e67e2b#diff-7f27a52aa4c9fc54be7cec53095d417e

I manually copied the code of the prior version of add.php into the file and the issue disappeared.

**Comment by WebDesignWorx** [comment]
OK, thanks.
I will handle it.

**Comment by WebDesignWorx** [comment]
Should handle it:
https://github.com/WBCE/WBCE_CMS/commit/112b7c1b796be79eb26111871dd2fad7dc4f2514

**Comment by instantflorian** [comment]
it does. 
Can you please make a PR with that change and the miniform changes ?

**Comment by WebDesignWorx** [comment]
I'm sorry, but I lack the time today.
Would be great if some one else could help out with it.

**Comment by instantflorian** [comment]
no problem, I'll do it then.
