### ISSUE TITLE
WBCE CMS 1.4.0 Arbitrary file upload Getshell

### ISSUE THREAD

**Issue by Invi0sible** [WBCE/WBCE_CMS#446]
Steps To Reproduce:
1.Login to the backstage as the admin;
2.change "Server Settings": No upload for this filetypes:
![image](https://user-images.githubusercontent.com/33925178/63244445-fa7b3080-c28f-11e9-96ae-789b975f763b.png)
3.upload evil file via /wbce/admin/media/upload.php
![image](https://user-images.githubusercontent.com/33925178/63244760-d835e280-c290-11e9-92ef-c9a833984cba.png)
![image](https://user-images.githubusercontent.com/33925178/63244785-e7b52b80-c290-11e9-99e0-3930e740fba2.png)
4. shell is http://10.211.55.8/wbce/media/shell.php
![image](https://user-images.githubusercontent.com/33925178/63244843-1206e900-c291-11e9-86c5-3bfac976185b.png)

**Comment by instantflorian** [comment]
Well... if a malicious user gains backend admin access, he can do more or less anything. So I don't think we can do very much about this.

**Comment by Invi0sible** [comment]
Well , if attacker can login as admin , it's very dangerous to upload evil php file and  getshell ,then do many more dangerous things. There are many ways to defense this. I think it's really a very serious problem.


------------------ 原始邮件 ------------------
发件人: "instantflorian"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 下午3:22
收件人: "WBCE/WBCE_CMS"<WBCE_CMS@noreply.github.com>;
抄送: "Invisible "<383195471@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [WBCE/WBCE_CMS] WBCE CMS 1.4.0 Arbitrary file upload Getshell(#446)




Well... if a malicious user gains backend admin access, he can do more or less anything. So I don't think we can do very much about this.

**Comment by instantflorian** [comment]
That's why the login is protected with username and password, and since 
1.4.0 better hardened against brute-force-attacks. We also increased the 
minimum password length and a strenth-o-meter to show the users how good 
their password is.
Nevertheless, thank you for your report, we will again discuss this 
issue in the team.

**Comment by Invi0sible** [comment]
OK.But the password may be leakaged. It's really very dangerous and it's easy to avoid the upload problem. Thoes are what I want to express. Thank you.




------------------ 原始邮件 ------------------
发件人: "instantflorian"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 下午3:35
收件人: "WBCE/WBCE_CMS"<WBCE_CMS@noreply.github.com>;
抄送: "Invisible "<383195471@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [WBCE/WBCE_CMS] WBCE CMS 1.4.0 Arbitrary file upload Getshell(#446)



That's why the login is protected with username and password, and since 
 1.4.0 better hardened against brute-force-attacks. We also increased the 
 minimum password length and a strenth-o-meter to show the users how good 
 their password is.
 Nevertheless, thank you for your report, we will again discuss this 
 issue in the team.

**Comment by dev4me** [comment]
With admin access I could upload a self made module...
I could create a php code block...
I could create a droplet..

With FTP access I could get admin access with 2 lines of code..
With admin access I could...

Strong usernames & passwords is the only solution!

**Comment by Invi0sible** [comment]
So, why the "No upload for this filetypes:" include "ph.*?" 




------------------ 原始邮件 ------------------
发件人: "Dev4me"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 下午3:41
收件人: "WBCE/WBCE_CMS"<WBCE_CMS@noreply.github.com>;
抄送: "Invisible "<383195471@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [WBCE/WBCE_CMS] WBCE CMS 1.4.0 Arbitrary file upload Getshell(#446)




With admin access I could upload a self made module...
 I could create a php code block...
 I could create a droplet..
 
With FTP access I could get admin access with 2 lines of code..
 With admin access I could...
 
Strong usernames & passwords is the only solution!

**Comment by instantflorian** [comment]
If you have a multi-user environement, you can/should create user 
accounts, which do not have acess to these options. These users can't 
change the upload restrictions and so they are not able to upload 
malicioius scripts.
Also, you can set access to installation of languages / modules and so 
on only for trustworthy users.
A usual editor account has just access to pages and media, not to users, 
add-ons, options and admintools.
So beside of strong username / passwords, administrators have to be 
careful to whom they give what kind f backend access. But that's 
actually the case at most CMS.

**Comment by webbird** [comment]
AFAIK the upload file types are for the media directory, so blacklisting *.ph* (and maybe some more like *.asp, *.ps*, *.pl) would be kinda solution. But as "dev4me" said, someone can still create a malicious module und upload it if he has the appropriate permissions. The only "solution" is to have as little users with backend access as possible and limit permissions as far as possible for all of them.

**Comment by instantflorian** [comment]
Reopen. At least we can consider that only the superadmin (id=1) should be able to change that setting.

**Comment by mrbaseman** [comment]
I agree. It's a setting which should be changed very carefully after all

**Comment by instantflorian** [comment]
solved in development branch.
Only the superadmin (UserID=1) can now change this settings.
