### ISSUE TITLE
use modern database management

### ISSUE THREAD

**Issue by rjgamer** [WBCE/WBCE_CMS#448]
https://forum.wbce.org/viewtopic.php?pid=26885#p26885

**Comment by Colinax** [comment]
solved with cd6a7141726e2ad07e90e24177efe2cbb4a98f15

**Comment by instantflorian** [comment]
Too many problems for now, we will give it a second try next year

**Comment by Colinax** [comment]
hopefully fixed with 49cff45784ea7f73c0dff3a07b4201b58238a1ec
