### ISSUE TITLE
Handling of disabled intro page

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#450]
https://forum.wbce.org/viewtopic.php?id=3111

- Rename intro.php?
- Remove?
- Apply a redirect from pages/intro.php to start page?

- Rewrite the complete thing, e.g. change it into a module/admintool and store the intro page contents in the database?

**Comment by WebDesignWorx** [comment]
This approach renames the intro.php page when not in use:
https://github.com/WebDesignWorx/WBCE_CMS/commit/96712f6035865ef56fa4b954350d078590c28a29

It is being renamed into ``intro.backup.php``.
It stays in the PAGES_DIRECTORY and once intro page is activated again, it's renamed back to ``intro.php``.

If it suffices...

**Comment by instantflorian** [comment]
I'm fine with that.

**Comment by instantflorian** [comment]
solved 1ab68478b387e0ccc4138db106ed9749c9d5670e
