### ISSUE TITLE
Module wysiwyg missing htmlspecialchars

### ISSUE THREAD

**Issue by dev4me** [WBCE/WBCE_CMS#453]
The wysiwyg module seems to be missing the function:
`    $content = htmlspecialchars($content);`
after fetching the content for the editor.

Trying to add a visible text like `<div class="myclass"></div>` will go wrong.

**Comment by Colinax** [comment]
Our Wysiwyg module is the same as in WB 2.8.3, but with a [change ](https://github.com/WBCE/WBCE_CMS/commit/b10bd110e1a8063046188db62cbb31496fcedf0f)made 14 days ago.

Do you have more information (what will go wrong) or describe the behavior in the forum.

**Comment by dev4me** [comment]
It's not the view.php, it is the modify.php that is the problem.
After replacing the MEDA_REL it should htmlspecialchars() the content to use it in the editor again.

**Comment by Colinax** [comment]
Ok I understand. Did you test it for compatibility?

**Comment by dev4me** [comment]
I found the difference by compairing WB versions, and tested by using it in my own (test) website.
Since it is only a backend modification I don't think it will have any other impact.
