### ISSUE TITLE
Page / Tool multi modules do not appear at group rights management

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#454]
https://forum.wbce.org/viewtopic.php?pid=27999#p27999
In this case:
Due to 
$module_function = 'page, tool'; 
miniform is handled as an admintool and not as a page and does not appear

**Comment by WebDesignWorx** [comment]
You mean, after setting $module_fumction to **page** only?

**Comment by instantflorian** [comment]
Sorry.  You're right, I meant setting it to "page" only.

**Comment by WebDesignWorx** [comment]
OK my friend.
Will have a look into it shortly.
I think it's just a matter of a database query where we now use
function = 'page' 
we should use 
function LIKE '%page%' 
(or some similar construct) instead.

**Comment by instantflorian** [comment]
The commit does not solve the issue.

**Comment by instantflorian** [comment]
...but this does 8-)
https://github.com/WBCE/WBCE_CMS/commit/02bfcfee2e490f5be5d38aa96535ed1d85ad4484
