### ISSUE TITLE
Better protection against wrongly executed install.php

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#461]
Yesterday a customer of mine deleted nearly 1/3 of his website due to running Add-Ons > Modules > install.php. All information stored in the specific module (here: itemz) was lost. Yes,, there is a warning, and yes, one can ask why this customer has access rights for the add-on page, but anyway.
We should rework that part to avoid such cases in the future, for example by a second confirmation (are you sure), mandatory entering the user's password for confirmation and/or making a backup of existing tables before they would be erased by install/update.php.
![2019-11-14_102537](https://user-images.githubusercontent.com/1433754/68843992-54419a00-06c9-11ea-81af-16d399cef5b4.jpg)

**Comment by dev4me** [comment]
I would suggest to show "install.php" just for the modules that are not yet installed.
Uploading through FTP and run install.php should still be possible.
Running install.php on a previous installed module is always a bad idea.

Running update.php could also be more intelligent :)
Only make update available when the version is different from the info.php version.

**Comment by instantflorian** [comment]
solved in development branch
