### ISSUE TITLE
Wrong timezone calculation

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#475]
There are still issues with timezones. 

Im WBCE Backend in den "Grundeinstellungen" stelle ich die Zeitzone auf GMT +2 ein und die Zeit wird korrekt mit zB. 11:41 angegeben.
Wenn ich unter "Meine Daten" die Zeitzone "Standardeinstellung" wähle, erwarte ich, das WBCE die Zeitzone der Grundeinstellung verwendet und auch 11:41 anzeigt. WBCE zeigt aber 13:41 anstatt 11:41 an.

Der Fehler ist reproduzierbar.

**Comment by Colinax** [comment]
Der Fehler wurde durch eine fehlerhafte Funktion in php selbst verursacht, des zusätzlich wurden die Fixes 866367f0481f3e1b81fc8457cbb2c5f1c9b0029f und e9f6aef4b7dab6b2fd0ff2adfd76e07b6e51cad6 implementiert um ein erneutes auftreten zu verhindern.
