### ISSUE TITLE
Frontend profile form does not accept correct password

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#476]
Any approach to change personal data via frontend form is refused, error message "You need to confirm with your current password.", although the correct password has been entered.

**Comment by instantflorian** [comment]
Forget it

**Comment by instantflorian** [comment]
This seems to be caused by #474 or #473 changes

**Comment by WebDesignWorx** [comment]
OK, will have a look into it.

**Comment by instantflorian** [comment]
Seems to be fixed, not reproduceable any more
