### ISSUE TITLE
Frontend Login does not show up when Homepage Redirection is enabled

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#483]
When Settings > Homepage redirection (Grundeinstellungen > URL-Umleitung zur Startseite) is enabled frontend login is not working, e.g. neither clickling on a link to a page with the visibilty registered or private, nor a direct link to accoun/login.php work. 
Instead a redirection the visitor is redirected to the start page.

**Comment by instantflorian** [comment]
a bit more precise: accoun/login.php is loaded, but from there the visitor is immediately redirected to the homepage.

**Comment by Colinax** [comment]
fixed with e0b488e72608ee0caccd42dd9d1a78d83e26a525
