### ISSUE TITLE
Time-based publishing of section ignores timezone settings

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#489]
publishing date and end date of a section have to be entered in GMT although another timezone is selected (for the current user as well in the general settings). E.g. if a section should be published at 07:30 GMT+2, and GMT+2 is set at settings and preferences, you have to choose 05:30 in the manage section view. The same for the end date/time.

**Comment by Colinax** [comment]
fixed with 96de0f97945ca4d79cd4ce769a23f206a590ce22
