### ISSUE TITLE
[ Security Issue ] Rename Function Restrict Bypass

### ISSUE THREAD

**Issue by Jindom** [WBCE/WBCE_CMS#490]
Hi Team,

Please note that there is a possible way to bypass the restriction and manage to upload a malicious php file to the system.
The vulnerable code located in /admin/media/rename2.php

![image](https://user-images.githubusercontent.com/26808448/93315191-528eb880-f83d-11ea-8fb9-1c67ffde20eb.png)

There aren't any filtering and protection against user's input "name" and "extension".
A user may upload a file called phpinfo.txt and rename it to phpinfo.php by entering the "name" to "phpinfo.ph" "extension" to "p". The following screenshot shows that the malicious user successfully upload phpinfo.php file to the webapp directory.

![image](https://user-images.githubusercontent.com/26808448/93316005-42c3a400-f83e-11ea-8e4d-6c91b4d9de78.png)

![image](https://user-images.githubusercontent.com/26808448/93316045-4f47fc80-f83e-11ea-84ca-d7d6512bda05.png)

**Comment by instantflorian** [comment]
Woops, thanks for the advice. 
Fixed with 462864b6fe5ca16aea882fe515cd1124381c1699
