### ISSUE TITLE
Automatic zipping / deleting of logfiles generated by errorloger module

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#492]
The file /var/logs/php_error.log can become very, very huge if a site has heavy traffic. Since even notices, which do not break the function of the website, are logged, the site administrator would not even notice the issues until the website slows down or stops working completely due to logfiles with 20.000.000 entries. (This really happened.)
So we urgently need a solution to zip/delete the logfile from time to time automatically, and/or an option to configure which errorlevel shoud be logged and/or a warning mechanism if the file gets too large.
If all this is not possible, the module has to be removed from core, since many non-technical skilled WBCE users will never have a look at the logfile anyway.

**Comment by webbird** [comment]
Possible solution A:

* Add date to logfile name = create a new file for every day
* Delete files older than X days

Possible solution B: Log file rotation

* Set max file size, f.e. 5 MB
* Rotate logs: .log -> .log1, .log1 -> .log2, ...
* Keep X files, f.e. 10

**Comment by dev4me** [comment]
My personal idea:
A website writing 20 million notices/warnings/errors should be fixed first instead of "shooting the messenger".

**Comment by instantflorian** [comment]
yes, that was a very special case and the entries were caused by an 
extra application which was wrapped into WBCE. But we also had some 
posts about the logfile flooding the server in the forum, and there is 
generally in my opinion no use of logfiles with hundered or thousand 
equal entries.
But nevertheless, I'm sad that you read my post as "shooting the 
messager" idea. It was not meant as this, just as an idea/wish for 
improving this useful module.

**Comment by dev4me** [comment]
You should read "shooting the messenger" as, fixing the reporting module instead of fixing the cause of the problem. (it was not taken personal :)

I agree, such a big erorlog is not usable, but an auto-remove/auto-rename function should at least warn the system admin (by mail).

**Comment by webbird** [comment]
You're both right, please don't fight. Let's just find a good solution.

**Comment by dev4me** [comment]
Simple solution for anyone with large errorlogs.
https://dev4me.com/modules-snippets/opensource/logrotate/

**Comment by instantflorian** [comment]
Thank you very much for the extra fast solution!
