### ISSUE TITLE
302 redirections on multilingual pages

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#497]
- on websites with more than one language, language redirects are created as "302" redirects
- even worse: they do not work if cookies are disabled by client or config.php direction, instead, an endless redirection error appears
This causes not only huge SEO / crawling problems, but also makes websites under certain circumstances inacessable. 

See https://forum.wbce.org/viewtopic.php?pid=36492#p36492

**Comment by Colinax** [comment]
From a technical point of view, the 302 diversions are not possible any other way and "multilingual" is incompatible with the "no cookie feature" see Release notes from 1.4.4.

**Comment by instantflorian** [comment]
Sorry, but as the user described in the forum the issue appears in general, if the user does not allow cookies. So the sites are not accessable for users with very restictive privacy rules and/or devices which are not able to set cookies. Also one cannot be sure if crawler can set cookies. So we need a solution that multiingual sites are also accessable w/o cookies.

**Comment by digitalbricks** [comment]
I just posted the modified files for my suggested fix in the forum thread: [https://forum.wbce.org/viewtopic.php?pid=36629#p36629](https://forum.wbce.org/viewtopic.php?pid=36629#p36629).
Could you please have a look on that?

**Comment by Colinax** [comment]
the 302 redirect is fixed with 1ff00c423bc24e9f533c2951bc6bc574e377cdf2
