### ISSUE TITLE
PHP8: SM2 undefined constant error

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#509]
[Exception] There was an unknown exception: Undefined constant "SM2_DEBUG" in line (38) of /modules/show_menu2/include.php

Solution (probably) https://forum.wbce.org/viewtopic.php?pid=36320#p36320

**Comment by Colinax** [comment]
fixed with 3bf26a104865d5c5602e0a9199f810963f3fc4f4
