### ISSUE TITLE
Missing link to signup form in form_login.twig

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#511]
The login form found at /modules/tool_account_settings/templates has no link to the signup form. If frontend registration is enabled, there should be a link or button displayed which leads to the singup form for new users.

**Comment by WebDesignWorx** [comment]
Handled with commit #536 (see screenshots)

![image](https://user-images.githubusercontent.com/9767034/217960807-1c705497-a446-48a5-9730-13d53c89185c.png)
![image](https://user-images.githubusercontent.com/9767034/217960834-92017aab-5848-4d3d-a0e2-1bf512180a49.png)

**Comment by instantflorian** [comment]
Sorry, but the Sign-up form should only be visible if frontend registration up is active.

**Comment by WebDesignWorx** [comment]
OK, please check with one the latest commits (#537)
Should work properly now.
