### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [WBCE/WBCE_CMS#514]
Hey there!

I belong to an open source security research community, and a member (@maxway2021) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Colinax** [comment]
I have created a Security.md for you. If email is too insecure for you, you can also reach us through our forum

**Comment by JamieSlome** [comment]
@Colinax - you should receive an e-mail from our system shortly with further details about the security issue (cc @maxway2021).

Otherwise, you can view the report directly here (private to maintainers only):

https://huntr.dev/bounties/c330dc0d-220a-4b15-b785-5face4cf6ef7/
