### ISSUE TITLE
Update check breaks backend login when connection to Github impossible

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#516]
When WBCE is installed on a local machine or intranet without internet access (or maybe behind a firewall), backend login fails due to connection time out by /include/GitHubApiClient/GitHubApiClient.php

(This is another issue than the failing update check when cURL is not available)

**Comment by Colinax** [comment]
This is already fixed with https://github.com/WBCE/WBCE_CMS/commit/b4c167075326f7f748341eb2398b4ded3ffc430b
