### ISSUE TITLE
Forgot password form not working when session cookies are disabled

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#517]
When the flag `define('NO_SESSION_COOKIE',true);` is set in the config.php, it is not possible to submit forms which use the WBCE built in captcha mechanism. 
But: Since the "Forgot password" form uses that captcha too to avoid brute force attacks, it is no longer possible to get a new password if session cookies are disabled. 
Probably the only solution is to show the captcha only if the flag NO_SESSION_COOKIE is not set.

**Comment by Colinax** [comment]
This is an already known Issue by design see [release notes](https://forum.wbce.org/viewtopic.php?id=3748)

**Comment by instantflorian** [comment]
Issue wieder aufgemacht. Auf Kontaktformulare kann man verzichten bzw. bei diesen das Captcha ausschalten. Beim Passwort-Vergessen-Formular haben die Nutzer:innen nicht diese Möglichkeit, deshalb muss das mMn systemseitig abgefangen werden.

**Comment by Colinax** [comment]
@instantflorian ich hab mir deinen Code und den Entwicklungsthread auf die schnelle angesehen.

In der wsession.php#L70 gibt es einen pattern, hier sollte es reichen den include hinzuzufügen aber bitte den entsprechenden Thread berücksichtigen, da es Nebenwirkungen haben könnte.
