### ISSUE TITLE
PAGE SPACER does not work

### ISSUE THREAD

**Issue by a6smile** [WBCE/WBCE_CMS#519]
I had try to change page spacer on wbce 1.5.3 but seem this does not work. also, default page created are use "_" instead "-"

**Comment by BerndJM** [comment]
20 test pages later I found the bug (I think).
In functions-utf8.php in line 493 the _ is hardcoded, if I replace it with PAGE_SPACER it seems to work as desired.
Can someone please check this against?

Bold thesis: this has never worked before, because this place seems to have "always" looked like this ;-)

**Comment by mrbaseman** [comment]
unfortunately, I can't confirm. I have a page called "über mich" and without having changed the page spacer it seems to default to '-' and no matter what I use as PAGE_SPACER, the '-' is used , even when I save the page again after changing the setting. 
So, we should rather find a hard coded '-' somewhere or find out why the setting for page_spacer is not loaded properly or where it is not used as expected

**Comment by dev4me** [comment]
> 20 test pages later I found the bug (I think). In functions-utf8.php in line 493 the _ is hardcoded, if I replace it with PAGE_SPACER it seems to work as desired. Can someone please check this against?

This is only used to replace special characters that are not allowed in the filename. It is not used for whitespaces.

> unfortunately, I can't confirm. I have a page called "über mich" and without having changed the page spacer it seems to default to '-' and no matter what I use as PAGE_SPACER, the '-' is used , even when I save the page again after changing the setting. 

When the page is previously saved, that filename will not change after changing the PAGE_SPACER. It will only work for new created pages or when you manually change the filename using whitespaces.

**Comment by BerndJM** [comment]
> This is only used to replace special characters that are not allowed in the filename. It is not used for whitespaces.

However, this place definitely replaces whitespaces with underscore (in the original state).
Thus, replacing whitespaces with PAGE_SPACER later in the chain has no effect anymore.

**Comment by mrbaseman** [comment]
Right. I can confirm that the proposed fix works. 

And as dev4me writes, once the filename is fixed when creating the page, is not changed anymore (unless one changes it manually in the preferences of an existing page). This makes sense.
