### ISSUE TITLE
Menu Link that does real Links

### ISSUE THREAD

**Issue by NorHei** [WBCE/WBCE_CMS#52]
MEnu link only does 301 or 302 Redirects by now.
We need Menu Links that can do real Links.

**Comment by NorHei** [comment]
One step further we are :-)
Core now supports direct Links and WB links.

**Comment by NorHei** [comment]
http://forum.wbce.org/viewtopic.php?id=318

This was the preparation

**Comment by NorHei** [comment]
Moved to after 1.2.0 as i go for Module reworks after 1.2.x  . A new Variable is added to the core to make this more easy than before.

**Comment by instantflorian** [comment]
Additional info, just 2,5 years later: the backend of the module stops working, when an anchor link name includes an ' and it stops working too if any page of the website has no sections at all. Both leads to a javascript error which prevents the select boxes from being filled.

**Comment by instantflorian** [comment]
https://github.com/WBCE/WBCE_CMS/pull/355
