### ISSUE TITLE
script_js_sysvars variable URL overrides URL Constructor

### ISSUE THREAD

**Issue by noelli** [WBCE/WBCE_CMS#520]
I am experiencing an Issue with the Javascript Variables added by class.wb.php and am trying to understand why they are necessary. 

To be precise, the vars `var URL = WB_URL = 'https://.....';` because `URL` overrides a default Constructor named [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL).

I stumbled upon this while trying to use PDFjs on my website, which uses this constructor to load the PDF Files.

When removing the `URL` from class.wb.php everything works as expected:
`$sJsSysvars = "\t\tvar WB_URL = '" . WB_URL . "';";`

Is this Variable used somewhere by WBCE or are there known Issues when removing it?

**Comment by mrbaseman** [comment]
I didn't find any place where this is used in the WBCE core or the modules shipped with the core distribution.
However, it might be used by some of the modules... on the other hand WB:URL is widely used for this purpose...

**Comment by instantflorian** [comment]
URL as JS variable is/was needed by [the old colorbox snippet](https://addons.wbce.org/pages/addons.php?do=item&item=32), which was part of the core until 1.4.0.  It is not automatically removed on updates and might still be installed. If the URL variable is not set, a JS error is thrown and other JS might stop working, so we decided to keep the (indeed too generic named) variable.
You can remove URL (but not WB_URL) without issues if the colorbox snippet is not installed.

**Comment by noelli** [comment]
Okay, since this is a new installation and not even in production i'll remove it and make a note to check the PDF-Page after updating WBCE in the Future.
