### ISSUE TITLE
Bypass account protection

### ISSUE THREAD

**Issue by gozan10** [WBCE/WBCE_CMS#524]
Hi team,

I found a way to bypass account protection (not blocked when brute-force account).

Step: *this is demo some cases

1. If I log in wrongly too many times, it will be locked
![image](https://user-images.githubusercontent.com/70020521/200104280-6124bd02-b0e1-457e-9797-aa721b421da5.png)

2.  But i can pass it by insert X-Forwarded-For header, then brute-force without being locked (use intruder plugin of burp suite) 
![image](https://user-images.githubusercontent.com/70020521/200104617-cd1fb003-9cbf-432f-80df-da38d92c914d.png)

3. set payload to brute-force and start attack
![image](https://user-images.githubusercontent.com/70020521/200104745-c4f30bc2-bf80-4c00-a8d8-cac5d73cf65b.png)
![image](https://user-images.githubusercontent.com/70020521/200104753-87d90ff6-4a0b-4f5e-962f-b5f32b9187ae.png)

4. Result find user (bypass account protection without blocked) 
![image](https://user-images.githubusercontent.com/70020521/200104986-62abf4b4-6816-4846-8710-410ff572f081.png)

**Comment by instantflorian** [comment]
fixed in https://github.com/WBCE/WBCE_CMS/releases/tag/1.5.4. Thanks again for reporting.
