### ISSUE TITLE
XSS via modul post loop in Pages

### ISSUE THREAD

**Issue by gozan10** [WBCE/WBCE_CMS#525]
Hi team,

I find XSS via modul post loop in Pages

Step:
1. add section in manage sections
![image](https://user-images.githubusercontent.com/70020521/200109961-361312f5-6720-47ac-bf18-d746c2081d40.png)
![image](https://user-images.githubusercontent.com/70020521/200109987-777a03c1-3109-4690-ac1c-6d4c852cba6d.png)

2. add new post then choose options in modify page (a new post must be created for the setting to take effect)
![image](https://user-images.githubusercontent.com/70020521/200110051-1aee1570-b421-4e03-a056-bf9fc73d4925.png)
![image](https://user-images.githubusercontent.com/70020521/200110578-46c57f7d-8c85-49f9-b73f-99c0a4bbc2f2.png)

3. In Post Loop inject javascript
![image](https://user-images.githubusercontent.com/70020521/200110303-366e66e0-1cf7-4228-9b65-64a9969cd35b.png)

4. save and view
![image](https://user-images.githubusercontent.com/70020521/200110319-bc77ee05-6d01-4a9b-a716-0a5d4d71b798.png)

**Comment by instantflorian** [comment]
Commit 26b9c1a included in https://github.com/WBCE/WBCE_CMS/releases/tag/1.5.4
