### ISSUE TITLE
OPF Plugin Filter jQ Colorbox throws notices

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#529]
This
> [Notice] /include/phplib/template.inc:[543] from /include/phplib/template.inc:[616] Template->subst "Array to string conversion" 
appears when editing the jQ colorbox filter, due to the outdated phplib template engine which is still used there.

We will fix this lateron when the OPF dashboard is migrated to Twig template engine.

**Comment by WebDesignWorx** [comment]
ok, we handled it by moving away from the outdated phpLib Template Engine and using Twig.
