### ISSUE TITLE
There is Cross Site Scripting(xss) at the preferences Display Name

### ISSUE THREAD

**Issue by aomanbuaoman** [WBCE/WBCE_CMS#539]
After submission, display_name will be escaped in the escapestring function for special symbols
![image](https://user-images.githubusercontent.com/75356114/219852947-72c3a877-caf3-4ca0-ba13-d56844a734e3.png)
When saving to database, it will add \ in front of " to " , but it does not affect the front-end recognition of "
![image](https://user-images.githubusercontent.com/75356114/219852965-aa2c0345-c5e4-4b11-941d-8d55679bb36d.png)
When output to the frontend, it is not filtered
![image](https://user-images.githubusercontent.com/75356114/219852968-1183814f-2878-48c1-974e-841a06a00aba.png)
Enter payload on the submit page to submit
payload:  s" autofocus=autofocus onfocus=alert(1) "
![image](https://user-images.githubusercontent.com/75356114/219852982-e360af21-d5c5-4bd6-a4c7-d3dc98cceaa4.png)
Successful writing of xss
![image](https://user-images.githubusercontent.com/75356114/219852987-07a17387-84b3-46e6-87aa-084ebca02377.png)

**Comment by instantflorian** [comment]
Thank you for reporting the issue!
Fixed with https://github.com/WBCE/WBCE_CMS/commit/07a0debe8103a554dd32c557d6d41eda02da1f5b
