### ISSUE TITLE
commit #558 cause module files to be installed as droplets

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#560]
In #558 changes were made to the module install/update process.
On certain circumstances this leads to be module files treated as droplets, e.g. module files appear as droplets (which won't work of course). Currently, this issue can be easily reproduced with the nightly build of WBCE CMS (upcoming version 1.6.3) and any News With Images version > 5.0.19 (installing/upgrading).
See https://github.com/WBCE/News-with-Images/issues/99 , I've initially thought it would be a NWI issue, but it isn't - this does not happen with the current stable version.
![374803645-ba5ff243-eef4-439b-bdc7-d082840056b3](https://github.com/user-attachments/assets/12f48a74-c449-47c1-955c-566e3719c252)

**Comment by gchriz** [comment]
I found the reason for this. 
First results are posted to the forum here: https://forum.wbce.org/viewtopic.php?pid=44442#p44442

**Comment by instantflorian** [comment]
solved with #562
