### ISSUE TITLE
Replace the Date selector 

### ISSUE THREAD

**Issue by NorHei** [WBCE/WBCE_CMS#59]
Maybe replace it whith the Jquery UI one ?

**Comment by instantflorian** [comment]
*bump*

**Comment by NorHei** [comment]
As far as i remember there is only a date selector in the Pages Area ?
Or did i miss one ?
Module should be already there

**Comment by NorHei** [comment]
The module already installed , Pagetree Module still missing so its nowhere in use.

**Comment by cwsoft** [comment]
Changed milestone to vLater. This feature is connected to the reworked page_tree, which won´t make it into WBCE 1.2.0. Will be tackled together with the page_tree rework.
