### ISSUE TITLE
New improved and lightened installer

### ISSUE THREAD

**Issue by webbird** [WBCE/WBCE_CMS#6]
The installer should be enhanced and cleared out, see

http://forum.wbce.org/viewtopic.php?id=12

**Comment by webbird** [comment]
Also see issue #4

**Comment by instantflorian** [comment]
I'm stuck and my code is just crap. Can anybody else takeover reworking the installer?

**Comment by webbird** [comment]
Postponed to some later version

**Comment by WebDesignWorx** [comment]
What I would like to see in the installer is a database connection check in the first step.

Similar as in the http://www.mysqldumper.net/ installation process.

When the DB connection is given, you go ahead with the installation process (table prefix, site title, admin account data etc.)

This is just a suggestion, of course. ;-)
