### ISSUE TITLE
Don't forget to update changelog

### ISSUE THREAD

**Issue by NorHei** [WBCE/WBCE_CMS#78]
Forgot to update last release

**Comment by cwsoft** [comment]
Just copy [this script](https://github.com/WBCE/wbce_tools/blob/master/changelog_creator/changelog_creator.sh) one level above your local WBCE repository and invoke it from a Git bash via ../changelog_creator.sh to write the commit messages to the CHANGELOG.md. Then commit the updated CHANGELOG.md and push it to Github.

**Comment by Colinax** [comment]
fixed with d892d3e371ec55ecba2c8038778e781009e65b7c
