### ISSUE TITLE
Exclude directories from Backup

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WBCE_CMS#89]
it should be possible to select/deselect directories which should (not) be backupped to avoid timeouts (e.g. "media" or "piwik")

**Comment by NorHei** [comment]
Basically this should go on 1.3.x , and maybe we look for a real backup/restore solution then . 
One whithout timeout ?

**Comment by instantflorian** [comment]
yes, that would be good. Maybe there's a way to create the backup 
part-by-part and merge it finally.
